# GitHub Actions - Discord Webhook Server Auto Deployment
name: Deploy Discord Webhook Server

on:
  push:
    branches: [ main ]
    paths: 
      - 'hyunho/discord-webhook-server/**'
  
  workflow_dispatch: # Manual trigger

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  FUNCTION_NAME: discord-webhook-server

jobs:
  deploy:
    name: Deploy to Google Cloud Functions
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: hyunho/discord-webhook-server
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
    
    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --source . \
          --entry-point discord_webhook \
          --runtime python311 \
          --trigger http \
          --allow-unauthenticated \
          --memory 512MB \
          --timeout 60s \
          --max-instances 100 \
          --min-instances 0 \
          --set-env-vars WEBHOOK_GENERAL="${{ secrets.WEBHOOK_GENERAL }}" \
          --set-env-vars WEBHOOK_ALERTS="${{ secrets.WEBHOOK_ALERTS }}" \
          --set-env-vars WEBHOOK_LOGS="${{ secrets.WEBHOOK_LOGS }}"
    
    - name: Get Function URL
      id: get-url
      run: |
        URL=$(gcloud functions describe ${{ env.FUNCTION_NAME }} --format="value(httpsTrigger.url)")
        echo "FUNCTION_URL=$URL" >> $GITHUB_OUTPUT
    
    - name: Test Deployment
      run: |
        curl -s ${{ steps.get-url.outputs.FUNCTION_URL }} | jq .
    
    - name: Notify Discord (Optional)
      if: always()
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          MESSAGE="✅ Discord Webhook Server 배포 성공!\n🌐 URL: ${{ steps.get-url.outputs.FUNCTION_URL }}"
        else
          MESSAGE="❌ Discord Webhook Server 배포 실패"
        fi
        
        if [[ -n "${{ secrets.WEBHOOK_DEPLOY_NOTIFICATIONS }}" ]]; then
          curl -X POST "${{ secrets.WEBHOOK_DEPLOY_NOTIFICATIONS }}" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$MESSAGE\"}"
        fi